#include "renderer.h"
#include "win_i_o.h"
#include "utils.h"

// model_data.h is generated by tools/glb_to_header.py and kept out of git (it is
// ~47 MB). Pull the tree into the scene only when it has actually been generated,
// so a fresh checkout still builds and still shows the cube.
#if __has_include("model_data.h")
#include "model_data.h"
#define HAVE_TREE_MODEL 1
#endif

#define CUBE_COLOUR 0xFFCC3344   // one flat colour for the whole cube

int main(){
create_window();
int w,h;
get_window_size(&w,&h);

// cube half-size 100, front face z=500, back face z=600, pushed left of centre so
// it clears the tree. every vertex carries the same colour: there is no lighting,
// so a solid mesh renders as a flat silhouette either way.
Vectex cube_vertices[8]={
    {.x=-350,.y=-100,.z=500,.colour=CUBE_COLOUR}, // 0
    {.x=-150,.y=-100,.z=500,.colour=CUBE_COLOUR}, // 1
    {.x=-150,.y= 100,.z=500,.colour=CUBE_COLOUR}, // 2
    {.x=-350,.y= 100,.z=500,.colour=CUBE_COLOUR}, // 3
    {.x=-350,.y=-100,.z=600,.colour=CUBE_COLOUR}, // 4
    {.x=-150,.y=-100,.z=600,.colour=CUBE_COLOUR}, // 5
    {.x=-150,.y= 100,.z=600,.colour=CUBE_COLOUR}, // 6
    {.x=-350,.y= 100,.z=600,.colour=CUBE_COLOUR}, // 7
};

// 6 faces * 2 triangles = 12 tris = 36 indices.
// each quad split on diagonal a-c: (a,b,c) + (a,c,d).
uint64_t cube_connectors[36]={
    0,1,2, 0,2,3,   // front  (z=500)
    5,4,7, 5,7,6,   // back   (z=600)
    4,0,3, 4,3,7,   // left   (x=-350)
    1,5,6, 1,6,2,   // right  (x=-150)
    4,5,1, 4,1,0,   // bottom (y=-100)
    3,2,6, 3,6,7,   // top    (y= 100)
};

Object cube={
    .vertices=cube_vertices,
    .len_of_vertices=8,
    .connectors_sequence=cube_connectors,
    .len_of_connectors=36,
    .colour=CUBE_COLOUR,
};

#ifdef HAVE_TREE_MODEL
// the tree. model_data.h ships two index arrays over the same vertices:
// model_connectors (pairs, for wireframe mode) and model_tri_connectors (triples,
// for the raster path). Feed the raster path the triple list — handing it the pair
// list would read three-at-a-time through an array laid out two-at-a-time and draw
// garbage. Each vertex carries a colour sampled from the model's baseColorTexture,
// so the per-pixel colour lerp across each triangle reproduces the bark tones.
Object tree={
    .vertices=model_vertices,
    .len_of_vertices=MODEL_VERT_COUNT,
    .connectors_sequence=model_tri_connectors,
    .len_of_connectors=MODEL_TRI_CONNECTOR_COUNT,
};

Object scene[2]={cube,tree};
uint64_t scene_len=2;
#else
Object scene[1]={cube};
uint64_t scene_len=1;
#endif


size_t cores = get_number_of_cores();
printf("This is the number of cors %li\n",cores);
render_init(scene,scene_len,w,h);
render();
update_win((PixelCord*)get_frame_buffer());
set_up_event_handler();
return   EXIT_SUCCESS;
}
